package uz.uzkass.smartpos.supply.core.utils

import kotlinx.coroutines.CancellationException


internal inline fun <T, R> T.resultOf(block: T.() -> R): Result<R> {
    return try {
        Result.success(block())
    } catch (e: CancellationException) {
        throw e
    } catch (e: Exception) {
        Result.failure(e)
    }
}
